default:
  derniere_ingestion:
    a: '2026-09-05T22:44:29+00:00'
    chunks_indexes: 0
    duree_secondes: 0.1
    fichiers_en_echec: 0
    fichiers_ignores_inchanges: 7
    fichiers_traites: 0
    fichiers_trouves: 7
    statut: succes
  profil_domaine: default
  source: local
